# Generated by Django 4.0.1 on 2022-12-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('mpesa_transaction_code', models.CharField(max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fundraising_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraiser.fundraisingevent')),
            ],
        ),
    ]
