# Generated by Django 4.0.1 on 2022-12-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingevent',
            name='target_amount',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
