# Generated by Django 4.0.1 on 2022-12-19 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraiser', '0003_fundraisingevent_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingevent',
            name='amount_contributed',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='fundraisingevent',
            name='members',
            field=models.ManyToManyField(related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
