# Generated by Django 4.0.1 on 2022-12-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_fundraisingevent_amount_contributed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
